### SALONS
GET http://localhost:8000/api/salons
###
GET http://localhost:8000/api/salons/5
###
POST http://localhost:8000/api/salons
content-type: application/json

{
  "name_salon":"xxxx", 
  "address":"4, impasse du pigeonnier",
  "city":"Paris",
  "zip":"75310",
  "dept_id":"75",
  "date_open":"2024-04-20"
}
###
PATCH http://localhost:8000/api/salons/5
content-type: application/json

{
  "name_salon":"Beauty salon", 
  "dept_id":"31A"
}
###
DELETE http://localhost:8000/api/salons/4

### REPORTS
GET http://localhost:8000/api/reports
###
GET http://localhost:8000/api/reports/2
###
POST http://localhost:8000/api/reports
content-type: application/json

{  
  "salon_id":5,
  "period":"2024-03-18", 
  "nb_etp":2.56,
  "turn_around":55002.36
}
###
PATCH http://localhost:8000/api/reports/8
content-type: application/json

{
 "nb_etp":2.5,
  "turn_around":25658.2,
  "salon_id":55
}
###
DELETE http://localhost:8000/api/reports/9

### USERS
GET http://localhost:8000/api/users
###
GET http://localhost:8000/api/users/2
###
POST http://localhost:8000/api/users
content-type: application/json

{  
  "salon_id":5,
  "last_name":"MARTINEZ",  
  "first_name":"Henri29",
  "email":"xxxxx@xx.com",
  "pwd":"1234H67£"
}
###
PATCH http://localhost:8000/api/users/1
content-type: application/json

{
 "email":"henri@xx.com",
 "salon_id":55
}
###
DELETE http://localhost:8000/api/users/2

