@user_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImxhc3RfbmFtZSI6Ik1BUlRJTkVaIiwiZmlyc3RfbmFtZSI6IkhlbnJpIiwiZW1haWwiOiJoZW5yaS50YWxmdW1pZXJAd2FuYWRvby5mciIsInJvbGUiOiJhZG1pbl9zYWxvbiIsImlhdCI6MTcxNDkxOTkzOSwiZXhwIjoxNzE0OTczOTM5fQ.Anh5FophWGN4LAUebkiVlpZCeZgAF_kMLi-CqHg7OWs
### SALONS
GET http://localhost:8000/api/salons
x-auth-token:{{user_token}}
###
GET http://localhost:8000/api/salons/5
x-auth-token:{{user_token}}
###
POST http://localhost:8000/api/salons
x-auth-token:{{user_token}}
content-type: application/json

{
  "name_salon":"yyyyy", 
  "address":"4, impasse du pigeonnier",
  "city":"Paris",
  "zip":"75310",
  "dept_id":"75",
  "date_open":"2024-05-20"
}
###
PATCH http://localhost:8000/api/salons/5
x-auth-token:{{user_token}}
content-type: application/json

{
  "name_salon":"Beauty salon", 
  "dept_id":"31A"
}
###
DELETE http://localhost:8000/api/salons/1
x-auth-token:{{user_token}}

### REPORTS
GET http://localhost:8000/api/reports
x-auth-token:{{user_token}}
###
GET http://localhost:8000/api/reports/2
x-auth-token:{{user_token}}
###
POST http://localhost:8000/api/reports/input
x-auth-token:{{user_token}}
content-type: application/json

{  
  "salon_id":1,
  "period":"2024-04-18", 
  "nb_etp":2.56,
  "turn_around":55002.36
}
###
PATCH http://localhost:8000/api/reports/8
x-auth-token:{{user_token}}
content-type: application/json

{
 "nb_etp":2.5,
  "turn_around":25658.2,
  "salon_id":55
}
###
DELETE http://localhost:8000/api/reports/1
x-auth-token:{{user_token}}

### USERS
GET http://localhost:8000/api/users
x-auth-token:{{user_token}}
###
GET http://localhost:8000/api/users/27
x-auth-token:{{user_token}}
###
POST http://localhost:8000/api/register
content-type: application/json

{  
  "last_name":"MARTINEZ   ",  
  "first_name":"  Henri  ",
  "email":"henri.talfumier@wanadoo.fr  ",
  "pwd":"1234H67£"
}
###
POST http://localhost:8000/api/register
content-type: application/json

{  
  "salon_id":1,
  "last_name":"MARTINEZ   ",  
  "first_name":"  Henri5 ",
  "email":"henri.talfumier@gmail.com  ",
  "pwd":"1234H67£"
}
###
GET http://localhost:8000/api/validate/27/1
x-auth-token:{{user_token}}
content-type: application/json

###
POST http://localhost:8000/api/login
content-type: application/json

{ 
  "email":"henri.talfumier@wanadoo.fr",
  "pwd":"1234H67£"
}
###
PATCH http://localhost:8000/api/profile
x-auth-token:{{user_token}}
content-type: application/json

{
 "email":"henri12@xx.com",
 "salon_id":5
}
###
DELETE http://localhost:8000/api/profile
x-auth-token:{{user_token}}

